server:
    addr: :8000
    read_timeout: 5s
    write_timeout: 5s
    idle_timeout: 500ms
shard_count: 8
locations:
    /: {}
    /random_joke/:
        upstream:
            name: backend-1
            addr:
                - official-joke-api.appspot.com
buffer_size: 8192
load_balancing_alg: round_robin
